---
-
  name: tap hombrew repos
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items:
    - caryll/tap
-
  name: install libraries and tools
  homebrew:
    name:
      - otfcc-mac64
      - ttfautohint
    state: latest
-
  name: install latex
  homebrew_cask:
    name: mactex
    state: latest
