---
-
  name: clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"
-
  name: create symlinks to home directory
  file:
    src: "{{ dotfiles_dir }}/{{ item }}"
    dest: "{{ home_dir }}/{{ item }}"
    state: link
  with_items: "{{ dotfiles }}"
