---
-
  name: clone dotfiles repo
  git:
    repo: https://github.com/MechanicalPig/.dotfiles.git
    dest: "{{ dotfilesdir }}"
-
  name: create symlinks to home directory
  file:
    src: "{{ dotfilesdir }}/{{ item }}"
    dest: "{{ homedir }}/{{ item }}"
    state: link
  with_items: "{{ dotfiles }}"
