---
-
  name: install homebrew packages
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ homebrew_packages }}"
-
  name: install homebrew cask applications
  homebrew_cask:
    name: "{{ item }}"
    state: installed
  with_items: "{{ homebrew_cask_applications }}"
